### ISSUE TITLE
bcmwl-kernel-source (wifi driver) broken with linux core 5.18 and above

### ISSUE THREAD

**Issue by hsuhyu** [pop-os/bcmwl#4]
There is already a fix with the following link:

https://launchpad.net/ubuntu/+source/bcmwl/6.30.223.271+bdcom-0ubuntu9

**Comment by jacobgkau** [comment]
The fix has been merged; after it's released in https://github.com/pop-os/repo-release, the update will be available through your regular updates (Pop!_Shop, the automatic updater if enabled, or `sudo apt update`/`sudo apt full-upgrade`.)

**Comment by hsuhyu** [comment]
Nice work from Pop!_OS!

**Comment by ganakee** [comment]
This needs to be re-opened as the "fix" does not work. 
In fact, the "fix" made the situation worse. The "fix" blows away something so one cannot even boot into older kernels and have WI-FI. The "fix" does not enable WI-FI on my system and in fact deletes WI-FI from all kernels. (This was not the case before applying the broken "fix." I was able to boot into 5.17 with WIFI.

At least on my system, the "fix" itself is broken.

**Comment by hsuhyu** [comment]
Download and install this: http://launchpadlibrarian.net/613905985/bcmwl-kernel-source_6.30.223.271+bdcom-0ubuntu9_amd64.deb fixed mine.

**Comment by mmstick** [comment]
That's the same version that was released.

**Comment by hsuhyu** [comment]
The pop shop version did not work three hours ago. Not sure about now.

**Comment by mmstick** [comment]
You're referring to an older version that was replaced two hours ago.

**Comment by hsuhyu** [comment]
Here is the version on the pop shop now which to me is the same as three and half hours ago when I tried but not working.

![image](https://user-images.githubusercontent.com/109746202/180346654-6719549f-5726-480c-a94a-f05c2e8254c2.png)

**Comment by mmstick** [comment]
That's the previous version

**Comment by hsuhyu** [comment]
The version on the Pop_shop is the latest this morning. I have successfully updated it and all working now. Thanks!
